### ISSUE TITLE
Blocking calls detected

### ISSUE THREAD

**Issue by aqwserf** [chriscamicas/gazdebordeaux-ha#4]
Salut !
Je viens de m'apercevoir que HA peste contre des appels bloquants venant de cette intégration:
```
Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/pytz/zoneinfo/Africa/Abidjan', 'rb') inside the event loop by custom integration 'gazdebordeaux' at custom_components/gazdebordeaux/gazdebordeaux.py, line 59: paris_tz = pytz.timezone('Europe/Paris') (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/chriscamicas/gazdebordeaux-ha/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/gazdebordeaux/__init__.py", line 18, in async_setup_entry await coordinator.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in async_config_entry_first_refresh await self._async_refresh( File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh self.data = await self._async_update_data() File "/config/custom_components/gazdebordeaux/coordinator.py", line 87, in _async_update_data totalUsage: TotalUsageRead = await self.api.async_get_total_usage() File "/config/custom_components/gazdebordeaux/gazdebordeaux.py", line 59, in async_get_total_usage paris_tz = pytz.timezone('Europe/Paris') 
```

Rien de bien méchant je pense mais je tenais tout de même à le remonter.

Merci !

**Comment by chriscamicas** [comment]
C'est réglé dans la dernière version [1.1.1](https://github.com/chriscamicas/gazdebordeaux-ha/releases/1.1.1)
merci pour avoir remonté le problème
